/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoamiRouteImport } from './routes/whoami'
import { Route as ReadRouteImport } from './routes/read'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingsIndexRouteImport } from './routes/writings/index'
import { Route as Writings2RouteImport } from './routes/writings/2'
import { Route as Writings1RouteImport } from './routes/writings/1'

const WhoamiRoute = WhoamiRouteImport.update({
  id: '/whoami',
  path: '/whoami',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingsIndexRoute = WritingsIndexRouteImport.update({
  id: '/writings/',
  path: '/writings/',
  getParentRoute: () => rootRouteImport,
} as any)
const Writings2Route = Writings2RouteImport.update({
  id: '/writings/2',
  path: '/writings/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Writings1Route = Writings1RouteImport.update({
  id: '/writings/1',
  path: '/writings/1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/read': typeof ReadRoute
  '/whoami': typeof WhoamiRoute
  '/writings/1': typeof Writings1Route
  '/writings/2': typeof Writings2Route
  '/writings/': typeof WritingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/read': typeof ReadRoute
  '/whoami': typeof WhoamiRoute
  '/writings/1': typeof Writings1Route
  '/writings/2': typeof Writings2Route
  '/writings': typeof WritingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/read': typeof ReadRoute
  '/whoami': typeof WhoamiRoute
  '/writings/1': typeof Writings1Route
  '/writings/2': typeof Writings2Route
  '/writings/': typeof WritingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/projects'
    | '/read'
    | '/whoami'
    | '/writings/1'
    | '/writings/2'
    | '/writings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/projects'
    | '/read'
    | '/whoami'
    | '/writings/1'
    | '/writings/2'
    | '/writings'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/projects'
    | '/read'
    | '/whoami'
    | '/writings/1'
    | '/writings/2'
    | '/writings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  ReadRoute: typeof ReadRoute
  WhoamiRoute: typeof WhoamiRoute
  Writings1Route: typeof Writings1Route
  Writings2Route: typeof Writings2Route
  WritingsIndexRoute: typeof WritingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whoami': {
      id: '/whoami'
      path: '/whoami'
      fullPath: '/whoami'
      preLoaderRoute: typeof WhoamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings/': {
      id: '/writings/'
      path: '/writings'
      fullPath: '/writings/'
      preLoaderRoute: typeof WritingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings/2': {
      id: '/writings/2'
      path: '/writings/2'
      fullPath: '/writings/2'
      preLoaderRoute: typeof Writings2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings/1': {
      id: '/writings/1'
      path: '/writings/1'
      fullPath: '/writings/1'
      preLoaderRoute: typeof Writings1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  ReadRoute: ReadRoute,
  WhoamiRoute: WhoamiRoute,
  Writings1Route: Writings1Route,
  Writings2Route: Writings2Route,
  WritingsIndexRoute: WritingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
